### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by PHorneij** [stuartridout/LiveEventsPBIX#1]
I'm totally new to Power BI (this Teams reporter is my first reason to use it) and was attempting to update it so that it would adjust to our time zone (EST5EDT, aka gmt-5/gmt-4) so that the people that would be looking at this wouldn't have to mentally adjust for the time zone change.  I've messed around with it a bit and was able to add a column that does the math on the HR column but can't get either of the time columns to use it.  I've also tried using DateTimeZone.ToLocal to do the adjustment but whatever I do errors out.  Would you be so kind as to update this awesome tool to allow for time zone adjustments please?
Thank you!

**Comment by stuartridout** [comment]
@PHorneij the report was updated a week ago to change the UTC values into local time.  

Do you have the latest version? 

When you are on the event page or the Q&A page do they have a comment at the bottom that the times displayed are UTC?

**Comment by PHorneij** [comment]
Hi Stuart,

 

Yes, the version I have has the note on the bottom about UTC, so I guess that’s not the latest.  I downloaded the zip today but I’ll just clone it and check that one out.

 

Thanks!

 

-=Phil

**Comment by stuartridout** [comment]
Apologies @PHorneij but the most up to date PBIX wasn't uploaded correctly.  This has now been updated so there shouldn't be a UTC warning and the report should show local time.

**Comment by PHorneij** [comment]
Hi Stuart,

 

Thank you for that, I appreciate it!

 

Best,

-=Phil Horneij
