### ISSUE TITLE
DateFormat Error

### ISSUE THREAD

**Issue by brunofreitasbr** [stuartridout/LiveEventsPBIX#2]
Hello, I'm using your PBI template and everything except the Q&A Insights is running fine. I'm facing some problems with RoundedTime and ActualTime (I think that is an UTC problem).

Here is the error:

DataFormat.Error: We couldn't parse the input provided as a DateTimeZone value.
Details:
    06/13/2020 01:30 +00:00

Can you give me some guidance thought this error? Thanks!

**Comment by stuartridout** [comment]
@brunofreitasbr there is a new version of the report coming in the next couple of days which completely revisits the date processing.  I would hope that this resolves this for you.

**Comment by brunofreitasbr** [comment]
Oh, all right, I'll wait for your new version. Thank you for your answer!

Here is my alias (t-brdoss), if you could ping me when your new version comes out I would be very thankful.

**Comment by stuartridout** [comment]
Hi Bruno.   New version is updated on GitHub.  Can you try and see if this fixes it so I can close this issue.

Thanks

**Comment by PHorneij** [comment]
Hi Stuart,
As of today it's still broken and it appears that you accidentally renamed the MM and DD columns backward so it's getting an invalid date format when trying to convert it to Date/Time/Timezone.  I updated the rename and now mine works as expected.

Hope that helps!
-=Phil

**Comment by stuartridout** [comment]
@PHorneij which part of the query is wrong?  Is this when you are getting the Events table?

**Comment by PHorneij** [comment]
No, it was in the data transform for the QandA power query where the rename of the month (MM) and day (DD) columns were backward, so the transform failed any time the day (aka month) was > 12 making it an invalid date.  In this screen shot I have already fixed them.
![PowerBI](https://user-images.githubusercontent.com/66335266/85056548-627afb80-b16d-11ea-8323-7f7843cbc523.png)

**Comment by PHorneij** [comment]
Also the new updates are great!  I was working on doing the same changes but since I'm new to PBI you got there a lot faster than I did so thank you!

**Comment by tuta23** [comment]
Hello @stuartridout  -- It doesn't appear that the issue that @PHorneij  mentions about the MM and DD has been resolved in the current release.

**Comment by PHorneij** [comment]
> Hello @stuartridout -- It doesn't appear that the issue that @PHorneij mentions about the MM and DD has been resolved in the current release.

Hey @tuta23 - I just uploaded a new fork that fixes this issues along with some other fixes and updates.  Give it a try and make sure you get the new Excel template as well since that has also changed.
https://github.com/PHorneij/LiveEventsPBIX/tree/PHorneij-patch-1
